version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: addis-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: addis
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - addis-network

  backend:
    build: ./backend
    container_name: addis-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/addis?authSource=admin
      PORT: 3000
    depends_on:
      - mongodb
    networks:
      - addis-network

volumes:
  mongodb_data:

networks:
  addis-network:
    driver: bridge
